Feature/updated restructure 2
dmstr/yii2-filefly-module pull request #20
Opened 2021-02-23 13:06 UTC by amk0

Merged all the latest changes master into the restructure branch.
Added permission support in the actions
Updated remove recursive

2021-02-23 19:24 UTC, schmunk42 requested changes
@eluhr Didn't you refactor the code into single compnents several months ago, which would now be reverted?

2021-02-23 19:24 UTC, schmunk42 commented on Module.php
> +    public $deleteRecursive = true;
Please do not change the default, can be configured in project config.

2021-02-24 05:49 UTC, handcode commented
@schmunk42 this branch is based on the feature/restructure branch from @eluhr which was never merged #13

2021-03-02 12:11 UTC, merged

2021-03-02 12:11 UTC, schmunk42 commented
Thank you!